version = 0.1

[default.deploy.parameters]
stack_name = "cloud-portfolio-backend"
resolve_s3 = true
s3_prefix = "cloud-portfolio-backend"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "RDSHost=\"ubuntucrafts-db.cbeya2y8yewh.af-south-1.rds.amazonaws.com\" RDSDatabase=\"ubuntucrafts_db\""

[default.global.parameters]
region = "af-south-1"
